spring:

  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:user_microservice}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: validate


